AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FGIDailyTraderFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["lambda_function.lambda_handler"]
      Timeout: 900  # 15분
      MemorySize: 1024  # 1GB
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest